spring.application.name=rewards

#spring.application.name=RewardsAPI

#GET http://localhost:8080/api/rewards/101?startDate=2025-01-01&endDate=2025-03-31

server.port=8080

spring.datasource.url=jdbc:h2:mem:rewarddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console